version: '3'


services:


  # PHP-apache
  web:
    # используем для создания Dockerfile
    build: ./web
    # переменная окружения для Apache
    environment:
      - APACHE_RUN_USER:#1000
    # расшариваем проект в контейнер host:container (из .env)
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    ports:
      - 8080:80
    # рабочая директория, при подключении к контейнеру мы сразу в ней
    working_dir: ${APP_PATH_CONTAINER}


  db:
    # используем базовый образ
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    # переменная-пароль для БД
    environment:
      MYSQL_ROOT_PASSWORD: 2222
    # shared dir for Db  host:container
    volumes:
      - ${DB_PATH_HOST}:/var/lib/mysql


  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8060:80


  composer:
    image: composer:1.6
    # shared dir
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    working_dir: ${APP_PATH_CONTAINER}
    # исполняем команду при запуске (into working_dir)
    command: composer install

