version: '3.6'

services:

  nginx:
    build:
      context: ./nginx
    volumes:
      - ./:/symfony
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    restart: unless-stopped
    ports:
      - "8081:80"

  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ./:/symfony
    container_name: ${COMPOSE_PROJECT_NAME}-php-fpm
    depends_on:
      - mysql

  php-cli:
    build:
      context: ./php-cli
    volumes:
      - ./:/symfony
    command: sleep 10000
    container_name: ${COMPOSE_PROJECT_NAME}-php-cli

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db:/var/lib/mysql
    container_name: ${COMPOSE_PROJECT_NAME}-mysql
    restart: unless-stopped
    ports:
          - "33061:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"

volumes:
  mysql: