version: '3.6'

services:




  postgres:
    image: postgres
    volumes:
      - ./db_data:/var/lib/postgresql/data
    container_name: ${COMPOSE_PROJECT_NAME}-postgres
    restart: unless-stopped
    ports:
          - "54320:5432"
    environment:
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DB}"

volumes:
  postgres: