version: '3.6'

services:

  nginx:
    build:
      context: ./nginx
    volumes:
      - ../:/var/www/get_exp
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    restart: unless-stopped
    ports:
      - "8086:80"


  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ../:/var/www/get_exp
    container_name: ${COMPOSE_PROJECT_NAME}-fpm
    depends_on:
      - mysql
    environment:
          XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"
          PHP_IDE_CONFIG: "serverName=Docker"

  php-cli:
    build:
      context: ./php-cli
    volumes:
      - ../:/var/www/get_exp
    command: sleep 25000
    container_name: ${COMPOSE_PROJECT_NAME}-cli
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"

  redis:
    image: "redis:6-alpine"
    volumes:
      - ./redis_data:/var/lib/redis
      #- ./redis.conf:/usr/local/etc/redis/redis.conf
    container_name: ${COMPOSE_PROJECT_NAME}-redis
    restart: unless-stopped
    ports:
      - "63796:6379"

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: ${COMPOSE_PROJECT_NAME}-mysql
    restart: unless-stopped
    ports:
      - "33066:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"

volumes:
  mysql:
  redis:
