version: "3.9"

services:
  elasticsearch:
    image: elasticsearch:8.6.2
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=2222
    volumes:
      - ./es_data:/usr/share/elasticsearch/data
    container_name: ${COMPOSE_PROJECT_NAME}-elastic
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic

  kibana:
    image: kibana:8.6.2
    container_name: ${COMPOSE_PROJECT_NAME}-kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elastic      

volumes:
  es_data:
    driver: local

networks:
  elastic:
    name: elastic
    driver: bridge