version: '3.6'

services:

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db_data:/var/lib/mysql
      - ./sakila-schema.sql:/docker-entrypoint-initdb.d/a_schema.sql
      - ./sakila-data.sql:/docker-entrypoint-initdb.d/b_data.sql
    container_name: mysql_sakila
    restart: unless-stopped
    ports:
          - "33062:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"